/**
 * The tyre model: one simplified Pacejka-style curve, evaluated on a COMBINED
 * slip magnitude, plus the per-wheel normal loads that scale it.
 *
 * Combining the slips before evaluating the curve is what gives the friction
 * circle for free: longitudinal and lateral force are two components of a single
 * vector whose magnitude can never exceed `mu * load`. There is no separate
 * clamp to forget to apply.
 *
 * Pure functions only — no state, no integration. `dynamics.ts` owns the state.
 */

import type { TyreDefinition, VehicleDefinition, WheelId } from './vehicle';
import { GRAVITY, VEHICLE } from './vehicle';

/**
 * Normalised magic-formula shape: 0 at zero slip, exactly 1 at unit combined
 * slip (the peak), with a mild falloff beyond so over-slipping a tyre loses
 * grip instead of gaining it.
 */
export function tyreCurve(combinedSlip: number, t: TyreDefinition = VEHICLE.tyre): number {
  const c = t.curveShape;
  // Choose B so the peak lands exactly at combinedSlip = 1.
  const b = Math.tan(Math.PI / (2 * c));
  return Math.sin(c * Math.atan(b * Math.abs(combinedSlip)));
}

/** Slope of `tyreCurve` at zero slip — the normalised cornering/drive stiffness. */
export function tyreInitialSlope(t: TyreDefinition = VEHICLE.tyre): number {
  return t.curveShape * Math.tan(Math.PI / (2 * t.curveShape));
}

export interface TyreForce {
  /** Longitudinal force in the WHEEL frame (N), positive = pushes the car along the wheel. */
  readonly longitudinal: number;
  /** Lateral force in the WHEEL frame (N), positive = toward the wheel's left. */
  readonly lateral: number;
  /** Fraction of the available friction circle in use — 1 is the limit of grip. */
  readonly gripUtilisation: number;
}

/**
 * Force generated by one tyre at a given slip ratio, slip angle and normal load.
 * `slipAngle` is signed: positive means the contact patch is sliding toward the
 * wheel's left, so the tyre pushes right (negative lateral force).
 */
export function tyreForce(
  slipRatio: number,
  slipAngle: number,
  load: number,
  t: TyreDefinition = VEHICLE.tyre,
): TyreForce {
  if (load <= 0) return { longitudinal: 0, lateral: 0, gripUtilisation: 0 };

  const sx = slipRatio / t.peakSlipRatio;
  const sy = Math.tan(slipAngle) / t.peakSlipAngle;
  const s = Math.hypot(sx, sy);
  if (s < 1e-12) return { longitudinal: 0, lateral: 0, gripUtilisation: 0 };

  // One draw on one friction budget, split along the slip direction.
  const magnitude = t.peakFrictionCoefficient * load * tyreCurve(s, t);
  return {
    longitudinal: (magnitude * sx) / s,
    lateral: (-magnitude * sy) / s,
    gripUtilisation: magnitude / (t.peakFrictionCoefficient * load),
  };
}

/**
 * d(longitudinal force)/d(slip ratio) at zero slip — the STEEPEST slope the
 * curve ever has. The wheel-spin integration linearises the road reaction about
 * this value rather than the local slope, for two reasons: the linear region is
 * stiff enough to explode an explicit solver at 120 Hz, and past the curve's
 * peak the local slope goes to zero (or negative), which would leave the step
 * undamped exactly where a spinning wheel is ringing. Over-estimating the slope
 * only adds damping — it cannot move the equilibrium the solve settles at.
 */
export function longitudinalStiffness(load: number, t: TyreDefinition = VEHICLE.tyre): number {
  return (t.peakFrictionCoefficient * load * tyreInitialSlope(t)) / t.peakSlipRatio;
}

/**
 * Vertical load on each wheel (N): static weight distribution plus longitudinal
 * and lateral weight transfer about the CG height. Accelerations are the body's,
 * in the body frame. Loads are clamped at zero — a lifted wheel makes no force.
 */
export function wheelLoads(
  longitudinalAccel: number,
  lateralAccel: number,
  v: VehicleDefinition = VEHICLE,
): Readonly<Record<WheelId, number>> {
  const weight = v.mass * GRAVITY;
  const transferLong = (v.mass * longitudinalAccel * v.cgHeight) / v.wheelbase;

  const frontAxle = weight * v.frontWeightFraction - transferLong;
  const rearAxle = weight * (1 - v.frontWeightFraction) + transferLong;

  // Lateral transfer is shared by each axle in proportion to the weight it
  // carries. Accelerating to the left (+y) unloads the left-hand wheels.
  const frontRoll =
    (v.mass * v.frontWeightFraction * lateralAccel * v.cgHeight) / v.trackFront;
  const rearRoll =
    (v.mass * (1 - v.frontWeightFraction) * lateralAccel * v.cgHeight) / v.trackRear;

  return {
    frontLeft: atLeastZero(frontAxle / 2 - frontRoll / 2),
    frontRight: atLeastZero(frontAxle / 2 + frontRoll / 2),
    rearLeft: atLeastZero(rearAxle / 2 - rearRoll / 2),
    rearRight: atLeastZero(rearAxle / 2 + rearRoll / 2),
  };
}

function atLeastZero(value: number): number {
  return value > 0 ? value : 0;
}
